Repository axonops/axonops-workbench, pull requests merged in 2024-07, with the labels that each got.

#81 80 add slack team to readme
  README.md
Labels: documentation

#102 Release/0.1.0 beta1 rc4
  .github/workflows/linux-executable-arm64.yml
  .github/workflows/linux-executable.yml
  .github/workflows/macos-arm-executable.yml
  .github/workflows/macos-executable.yml
  .github/workflows/release.yml
  .github/workflows/windows-executable.yml
  config/app-config.cfg
  package.json
  requirements.txt
Labels: All OS

#107 DevTools closed by default
  .github/workflows/release.yml
  main/main.js
  package.json
Labels: All OS

#122 121 add os to build artefacts
  package.json
Labels: build

#136 Increase retries for compose
  custom_node_modules/renderer/docker.js
  renderer/js/default_docker_compose_yml.js
Labels: bug

#141 Rename cluster name to sandbox
  renderer/js/default_docker_compose_yml.js
Labels: enhancement, All OS

#167 Correct repo url
  package.json
Labels: bug

#171 Adds instructions for Homebrew
  README.md
Labels: documentation, Mac
